# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: TriJS Meetup
email: ryan@ryanhayes.net
description: > # this means to ignore newlines until "baseurl:"
  TriJS is a JavaScript meetup in Johnson City, Tennessee!
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://meetup.com/tri-js" # the base hostname & protocol for your site
twitter_username: TriJSMeetup
github_username:  trijs

# Build settings
markdown: kramdown
